org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

mod_id=buildaspell
mod_name=Build a Spell
mod_version=1.0.2
mod_group_id=buildaspell
mod_authors=Cyberday
mod_description=Advanced spell creation system with uncapped enchantments and limitless magical possibilities

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.0-beta
neo_version_range=[26.2.0.0-beta,)

loader_version_range=[4,)

modonomicon_version=1.130.0
